### ISSUE TITLE
centermask2

### ISSUE THREAD

**Issue by ghost** [davamix/cats-localization#2]
@davamix 

Lately, centermask2 was released, showing at certain cases, almost 2x faster while maintaining a comparable accuracy. It would be interesting to see centermask2 be integrated into this repo.
Have a look at [CenterMask-Lite](https://github.com/youngwanLEE/centermask2#centermask-lite), it is compatible with detectron2!

Waiting for your reply

**Comment by davamix** [comment]
Hey! @deepseek 

Thanks for the info, I didn't know CenterMask and looks very interesting. I was looking something to do real time inference and this could fit with my purpose.

Regarding to be integrated with this repo, I think I will create a new one because this repo is linked with this post: [https://davamix.net/posts/detecting-my-cats-with-Detectron2.html](https://davamix.net/posts/detecting-my-cats-with-Detectron2.html) and I don't want to change the code too much.

**Comment by ghost** [comment]
Good luck
