### ISSUE TITLE
No Class training

### ISSUE THREAD

**Issue by ghost** [davamix/cats-localization#3]
@davamix 
 My goal is to create a model that can run **fast on CPU** and is **light on ram**, along with being **accurate**.

- I tested training on [rpn_R_50_C4_1x](https://github.com/facebookresearch/Detectron2/blob/master/MODEL_ZOO.md#rpn--fast-r-cnn) since it is very fast and only uses 1.5GB ram noted.
- Before training, I changed train.py and test.py to `COCO-Detection/rpn_R_50_C4_1x.yaml`
- Note that I trained on the [cat dataset](https://drive.google.com/open?id=1o9zyd51QCqWG3DlArQnfH4q4clMVQmTY) that you provided.
Also [here is my trained model](https://drive.google.com/open?id=1GNtxcgaqXy14YBS9vQYVEgyzCK3PQrTB)

Once the model was trained, I ran test.py but I am getting an error:
```
(d2) home@home-desktop:~/p13/c2$ python ./src/test.py 
Traceback (most recent call last):
  File "./src/test.py", line 106, in <module>
    test_image(image_path)
  File "./src/test.py", line 38, in test_image
    pred_classes = (outputs.pred_classes).detach()
AttributeError: 'dict' object has no attribute 'pred_classes'
```

**Comment by davamix** [comment]
`outputs` is a dictionary, so to access to the `pred_classes` is through `outputs['instances'].pred_classes`

**Comment by ghost** [comment]
But what about when wanting to predict using `rpn_R_50_C4_1x` it's a `COCO-Detection` model not a `COCO-InstanceSegmentation` model, so classes are not required, that why it shows the error.

**Comment by davamix** [comment]
Sorry, I misread the type of the model.

Looking the documentation, the [predictor ](https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultPredictor) always returns a dictionary, but depending of the model, the values inside the dictionary are diferent. Check the the [Model Output Format](https://detectron2.readthedocs.io/tutorials/models.html#model-output-format).

So, instead of `outputs['instances'].pred_classes` you can use `outputs['proposals'].proposal_boxes`

Also, you can `print(outputs)` and see what values are inside and how they are named.

**Comment by ghost** [comment]
hmmmm... I was not able to create a working script.
Have a look at my rpn cats [trained model](https://drive.google.com/open?id=1GNtxcgaqXy14YBS9vQYVEgyzCK3PQrTB)
Upload the changed files so i can test.

**Comment by davamix** [comment]
Check this [gist](https://gist.github.com/davamix/ae8818ebba64458a9e19b481ad453b65).

In `test.py` I use `COCO-Detection/rpn_R_50_C4_1x.yaml` configuration with your trained model, then I printed some values from `outputs`.
