### ISSUE TITLE
Proposal visualization

### ISSUE THREAD

**Issue by ghost** [davamix/cats-localization#5]
#3 @davamix 

After training a proposal based model `rpn_R_50_C4_1x`, when testing using the modified [test.py](https://gist.github.com/deepseek/71b0beeee9db8e4ae2d5c611ffeddb87), values are show.

Now how to visualize the proposals into a `predicted.jpg`
show exact code

**Comment by davamix** [comment]
I don't know if Detectron2 has some utility like _draw_instance_predictions_ to draw those boxes but you can use OpenCV to draw the proposals.

The proposals is a [Boxes](https://detectron2.readthedocs.io/_modules/detectron2/structures/boxes.html#Boxes) type, so you can iterate over list and use the values (x1, y1, x2, y2) of each row in order to draw a [rectangle](https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#rectangle).

Check [this](https://www.geeksforgeeks.org/python-opencv-cv2-rectangle-method/) to know how to draw a rectangle.

**Comment by ghost** [comment]
thanks
