### ISSUE TITLE
Centermask2

### ISSUE THREAD

**Issue by ghost** [davamix/cats-localization#6]
@davamix 
Have you tested training using [Centermask2](https://github.com/youngwanLEE/centermask2)

**Comment by davamix** [comment]
Yes, I tested but the results were not really good in comparison with Detectron2, as you can see in the image.

I used the VoVNetV2-99 to train the model for 4200 iterations instead of 700 as I did with Detectron2. 

I uploaded the changes in _train.py_ and _inference.py_ to this [Gist](https://gist.github.com/davamix/3c2c63bb44ff43888eb432863c936a6e). If you want to test it, clone the Centermask2 repository and copy those files into the root folder, also copy the same _loader.py_ and the _data_ folder with the images.

I don't know why these results, maybe there is something wrong in the configuration, maybe the dataset is to small or it need to be trained for more iterations, it's a matter of more experiments.

![inference_0](https://user-images.githubusercontent.com/581193/77236624-97a09d80-6bc0-11ea-9893-b84d127a11f4.jpg)

**Comment by ghost** [comment]
hmmm...
i am currently training an `centermask_lite_V_19_slim_dw_eSE_FPN_ms_4x` model, it seems to take a long time to converge, but i will continue training.
stay tuned for results in the future

**Comment by ghost** [comment]
hmmmm.... 
I trained almost 70,000 iterations and the `total_loss: 0.6`, it wont go below 0.6
Tested training both `V_39` and `V_39`.
I posted an issue to the developer, awaiting his reply
https://github.com/youngwanLEE/centermask2/issues/21

**Comment by ghost** [comment]
samples
![inference_2](https://user-images.githubusercontent.com/49877135/77344992-11619400-6d45-11ea-9c18-dc0dd34a3c19.jpg)
![inference_0](https://user-images.githubusercontent.com/49877135/77345038-23dbcd80-6d45-11ea-9a7e-e63f35f4b6a4.jpg)
![inference_2](https://user-images.githubusercontent.com/49877135/77345065-2dfdcc00-6d45-11ea-8983-c815b7787c18.jpg)

**Comment by ghost** [comment]
you are right, Centermask2 is a waste of time
